apiVersion: v1
name: radix-operator
version: 1.12.16
appVersion: 1.31.15
kubeVersion: ">=1.22.0"
description: Radix Operator
keywords:
  - radix
home: radix.equinor.com
sources:
  - https://github.com/equinor/radix-operator
maintainers:
  - name: Omnia Radix Development Team
    email: Radix@StatoilSRM.onmicrosoft.com
deprecated: false
